package io.openems.edge.ess.refu;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;


@ObjectClassDefinition( //
		name = "ESS Refu", //
		description = "The energy storage system implementation of a Refu Ess.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";
	
	@AttributeDefinition(name = "Ess state", description = "Switches the ess into the given state, if default is used, ess state is set automatically.")
	EssState essState() default EssState.DEFAULT;
	
	@AttributeDefinition(name = "Operational state", description = "Switches the operatioanl state.")
	SetOperationMode operationState() default SetOperationMode.PQ_SET_POINT;	

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "";

	String webconsole_configurationFactory_nameHint() default "ESS Refu [{id}]";

}